version: "3.3"
services:
  app:
    container_name: srcbot
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      SESSION: $SESSION
      AUTH: $AUTH
      FORCESUB: $FORCESUB
